microsoft/spatialaudio-unity

README.md
While the documentation pages point to this repo, if you discover this repo via other means there's no obvious way to get back to the documentation. I updated the readme to point back at the docs just in case anyone finds themselves here first.
=> Update readme to point at documentation

Source/Spatializer/HoloLens2/IsacAdapter.cpp, Tools/runcmake.py
VS2019 CMake generator uses the build machine arch as the default which is a breaking change from vs2017 and prior (used to be Win32 if not specified). This is causing x86 spatializer dll to be incorrectly built as x64. This change explicitly sets the build architectures for different configurations. There was also a regression in MSVC that is causing a spurious warning with PA spatializer build which is fixed with a pragma.
=> Fix cmake gnerator arch options and PA warning

Source/Spatializer/HoloLens2/IsacAdapter.cpp, Tools/runcmake.py
UWP projects were inadvertently broken with the last CMake change causing the plugin load to fail for UWP apps.
=> Pass WindowsStore flags to CMake correctly

Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/.npmrc, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/package.json
This publishes the package to the public registry and scopes the package to Unity 2019.4 and greater (aligns with MRTK).
=> Publish UPM package to public registry

Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/Editor/Microsoft.SpatialAudio.Spatializer.Editor.asmdef, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/Editor/Microsoft.SpatialAudio.Spatializer.Editor.asmdef.meta, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/Editor/RoomEffectSendLevelEditor.cs, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/Microsoft.SpatialAudio.Spatializer.asmdef, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/Microsoft.SpatialAudio.Spatializer.asmdef.meta, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Scripts/RoomEffectSendLevel.cs
In preparation for UPM, any scripts need to be contained in an assembly definition. Otherwise, when imported into Unity via the Package Manager, you'll see the following: 
```
Script 'Packages/com.microsoft.spatialaudio.spatializer.unity/Scripts/RoomEffectSendLevel.cs' will not be compiled because it exists outside the Assets folder and does not to belong to any assembly definition file.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)
```
This PR adds both runtime and editor-only asmdef files, as well as adding namespaces to the corresponding scripts.
Recommend viewing with whitespace changes hidden, to make the actual additions more clear: …
=> Add asmdefs and namespaces to package scripts

Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/package.json
To align with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8425 and the author name used by other packages on this feed (like [MixedReality-WebRTC](https://github.com/microsoft/MixedReality-WebRTC/blob/3e3443516196d16f072f218f23348212bfccd4b9/libs/unity/library/package.json#L15) and [GpuStats](https://github.com/microsoft/MixedRealityToolkit/blob/0c6ee792922d04c474e915e7d49fd140b72949a8/GpuStats/UnityAddon/package.json#L15), I've updated the author name from "Microsoft Corporation" to "Microsoft".
Unity groups packages by their author in the UI, so this will help keep our packages grouped together!
=> Update author name in package.json

Pipelines/Templates/Package.yaml, Pipelines/Templates/Publish.yaml, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/.npmrc, Source/Plugins/IsacPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/package.json, Tools/upm_package.py
1. Publishing phase will now push the plugin to the public UPM feed.
2. Added "dry-run" support for testing to the UPM packaging script.
=> Publish plugin to public UPM feed

Pipelines/Templates/Publish.yaml
I missed the artifact folder name when specifying path to .npmrc. "dry-run" did not catch it but publishing from master didn't work because it defaulted to npmjs registry.
=> Fix npm artifact path for .npmrc

Pipelines/Templates/Package.yaml, Pipelines/Templates/Publish.yaml, Tools/upm_package.py
npm publish is still failing in master with the current SC under a system account. Switching to the SC that's known to work. Internal feed publishing was also inadvertently broken while adding dry-run support, this fixes it.
=> Try different SC and fix script break

Pipelines/Templates/Publish.yaml
Nuget package signing auth is failing on analog on-prem pool, I think this requires packagep-es pool.
=> Signing requires PackageES pool

Pipelines/Templates/Package.yaml, Pipelines/Templates/Publish.yaml, Pipelines/Templates/Sign.yaml, Source/Spatializer/HoloLens2/CircularBuffer.cpp, Source/Spatializer/HoloLens2/CircularBuffer.h, Source/Spatializer/HoloLens2/IsacAdapter.cpp, Source/Spatializer/HoloLens2/IsacAdapter.h
This change should fix issue #55. This crash seems to be from an underflow due to a race between the rendering thread and device change callback which leads to DropSamples changing the read position while the spatializer is in the middle of reading from CircularBuffer. I couldn't get a repro but was able to extract enough information from some of the dumps.
=> Guard device change and prevent underflow when dropping samples

Pipelines/Templates/Package.yaml, Pipelines/Templates/Sign.yaml
- Sign binaries based on a var
- Use {{ else }} clause for setting PackageVersion. Not sure why earlier builds didn't complain but apparently previous syntax where PackageVersion definition is overridden is not a valid and causes parsing error.
=> Conditionally sign bins

Samples/MicrosoftSpatializerSample/Packages/manifest.json, Samples/MicrosoftSpatializerSample/Packages/packages-lock.json, Samples/MicrosoftSpatializerSample/ProjectSettings/PackageManagerSettings.asset
Sample now uses the prerelease version on the public UPM feed.
=> Update package to public prerelease version

Samples/MicrosoftSpatializerSample/Assets/Master.mixer
Spatializer will not render audio without the mixer plugin. I think this was inadvertently stomped on during the merge from the feature branch.
=> Add "Microsoft Spatializer Mixer Plugin" effect to the master mixer 

Pipelines/Templates/Package.yaml, Pipelines/Templates/Publish.yaml
Analog On-Prem pool is going away and being replaced by Analog-Unity.  Switch over build pipeline to new agent pool.
=> Update agent pool to Analog-Unity

Source/CMakeLists.txt, Tools/packages.config
In preparation for merging develop to master due to the build pipeline updates for Analog OnPrem going away, update the HrtfDsp version to the latest non-prerelease version on the AIPMR feed.
Tested by importing built unity plugin package from a topic branch with this change and hooked up to a sound source to verify spatialization was functioning properly.
=> Update Unity plugin to use latest Flex DSP

Pipelines/Templates/Sign.yaml
The signing task couldn't find the file AudioPluginMicrosoftSpatializer.dll since the filename had changed.  Update filename to reflect current name.
=> Update filename to sign

Pipelines/Templates/BuildAndroid.yaml
Validation pipeline didn't run in MS ADO on Analog-1ES-WindowsLatest pool so move to the public pool since Android builds don't need anything special.
Validated both release and validation pipeline against this topic branch.
=> Move off Analog-1ES-WindowsLatest pool

Source/Plugins/CrossPlatformPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/Plugins/x86_64/HrtfDsp.dll.meta
this change fixes an error about missing dll in x86_64 builds
reported in https://github.com/microsoft/spatialaudio-unity/issues/83
=> added missing platform setting to HrtfDsp.dll metadata

Source/Plugins/CrossPlatformPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/CHANGELOG.md, Source/Plugins/CrossPlatformPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/CHANGELOG.md.meta, Source/Plugins/CrossPlatformPluginGenerator/Assets/Microsoft.SpatialAudio.Spatializer.Unity/package.json
Microsoft will be publishing their most recent Mixed Reality UPMs to the Unity Asset Store.  In prepartion for this, this Stapial Audio package must be updated to meet Unity's requirements.
The following were changed to meet Unity's requirements
- Minimum version of Unity updated to 2021.3.26f1. This is the minimium version of Unity supported by the UPM Asset Store.
- Added the `unityRelease`.  This is required by the UPM Asset Store.
- Added a CHANGELOG.md that follows the [Keep a Changelog](http://keepachangelog.com/en/1.1.0/) formatting.
- Added `documentationUrl`. This is required by the UPM Asset Store.
=> Updating unity package so it meets Unity Asset Store requirements

Pipelines/Templates/Sign.yaml
Add task to signing template to ensure .NET Core 2.1.x is installed as required by the ESRP signing task
=> Ensure .NET Core 2.1.x installed for signing
